%%% Real Time Wave Monitoring GUI

clear all
clf, close all
home
run SetPath

%% Visual options
BackgroundColor = [0.94 0.94 0.94];
FontColor = 'k';
FontUnits = 'points';
PanelFontSize = 10;
AxesFontSize = 10;
PanelBorderColor = 'w';
BorderType = 'line';
TabBackground = 'w';

%% Main Window, Tabs & Axes

% Figure
MainFigure = figure('Visible','off','Name','Real Time Wave Monitoring GUI',...
    'MenuBar','none','Units','normalized','Position',[.15 .2 .6 .6],...
    'Tag','MainFigure','Color',BackgroundColor,'NumberTitle','off',...
    'Toolbar','none');

% Tabs
MainTabs = uitabgroup(MainFigure,'Position',[.005 .2 .67 .8],'Tag','MainTabs');
tab1 = uitab(MainTabs,'Title','User Function','Tag','Tab1','BackgroundColor',TabBackground);
tab2 = uitab(MainTabs,'Title','Wave Height','Tag','Tab2','BackgroundColor',TabBackground);
tab3 = uitab(MainTabs,'Title','Protective Index','Tag','Tab3','BackgroundColor',TabBackground);
tab4 = uitab(MainTabs,'Title','Wave Potential','Tag','Tab4','BackgroundColor',TabBackground);

axesLocation = axes('Position',[.855 .75 .14 .23],'Tag','axesLocation','Visible',...
    'off','FontUnits',FontUnits,'FontSize',AxesFontSize);
axesArrow = axes('Position',[0 .35 .99 .65],'Tag','axesArrow','Visible',...
    'off','FontUnits',FontUnits,'FontSize',AxesFontSize,...
    'DataAspectRatio',[1 1 1]); xlim([-pi,pi]), ylim([-1,pi]) %[.85 .7 .15 .25]

axesPlot1 = axes('parent',tab1,'units','normalized','FontUnits',FontUnits,'position',...
    [0 0 1 1],'Tag','axesPlot1','Visible','off','FontSize',AxesFontSize,'Color','none'); box on
axesPlot2 = axes('parent',tab2,'units','normalized','FontUnits',FontUnits,'position',...
    [0 0 1 1],'Tag','axesPlot2','Visible','off','FontSize',AxesFontSize); box on
axesPlot3 = axes('parent',tab3,'units','normalized','FontUnits',FontUnits,'position',...
    [0 0 1 1],'Tag','axesPlot3','Visible','off','FontSize',AxesFontSize); box on
axesPlot4 = axes('parent',tab4,'units','normalized','FontUnits',FontUnits,'position',...
    [0 0 1 1],'Tag','axesPlot4','Visible','off','FontSize',AxesFontSize); box on

axesOmega2D = axes('Position',[.855 .54 .14 .18],'Tag','axesOmega2D','Visible',...
    'on','FontUnits',FontUnits,'FontSize',AxesFontSize,'XGrid','on','YGrid','on'); box on
axesTheta2D = axes('Position',[.855 .3 .14 .18],'Tag','axesTheta2D','Visible',...
    'on','FontUnits',FontUnits,'FontSize',AxesFontSize,'XGrid','on','YGrid','on'); box on

axes3D = axes('Position',[.7 .025 .295 .24],'Tag','axes3D','Visible',...
    'on','FontUnits',FontUnits,'FontSize',AxesFontSize,'XGrid','on','YGrid','on'); box on

%% Definition of the interface

tags = {
        %----Tools
        'ZoomXY'                 2
        'PanXY'                  2
        'Rotate'                 2
        %----PGD File Info
        'PGD_Panel'              0          
        'ElemType_Text'          0
        'ElemType_Value'         0
        'PeriodRange_Text'       0
        'PeriodRange_Value'      0
        'DirectionRange_Text'    0
        'DirectionRange_Value'   0
        %----Visualization
        'View_Panel'             0
        'View_Axes'              1
        'View_Mesh'              1
        'View_Bottom'            1
        'View_Plot'              1
        'View_Background'        1
        'View_BC'                1
        'View_PlotTransparency'  1
        'View_MeshTransparency'  1
        'View_BGTransparency'    1
        'View_BotTransparency'   1
        %----Incident Wave
        'Input_Panel'            0
        'Freq_Text'              0
        'Freq_Value'             1
        'Period_Text'            0
        'Period_Value'           1
        'Direction_Text'         0
        'Direction_Value'        1
        'PGDTerms_Text'          0
        'PGDTerms_Value'         1
        %----Coordinates
        'Coord_Panel'            0
        'XCoord_Text'            0
        'XCoord_Value'           0
        'YCoord_Text'            0
        'YCoord_Value'           0
        %----Solution info
        'Info_Panel'             3
        'Average_Text'           0
        'Average_Value'          0
        'Minimum_Text'           0
        'Minimum_Value'          0
        'Maximum_Text'           0
        'Maximum_Value'          0
        %----User Functions
        'UserFcn_Text'           0
        'UserFcn'                1
        'Omega_Text'             0
        'Theta_Text'             0
        'Plot3D_Text'            0
        %----Output Panel
        'Output_Panel'           0
        'Text_Output'            0
        };        
    
%% User interface elements

%------------- Tools   
ZoomXY = uitoggletool('TooltipString','Zoom','CData',...
    iconRead(fullfile('Callbacks/Icons','ZoomXY.gif')),'Separator','on',...
    'Enable','off');

PanXY = uitoggletool('TooltipString','Pan','CData',...
    iconRead(fullfile('Callbacks/Icons','PanXY.gif')),'Separator','on',...
    'Enable','off');

Rotate = uitoggletool('TooltipString','Rotate','CData',...
    iconRead(fullfile('Callbacks/Icons','Rotate.gif')),'Separator','on',...
    'Enable','off');
%--------------------------------------------------------------

%------------- PGD file info
PGD_Panel = uipanel('Title','PGD File Info','FontUnits',FontUnits,'BorderType',BorderType,...
    'TitlePosition','centertop','HighlightColor',PanelBorderColor,...
    'Position',[.685 .48 .15 .1],'FontSize',PanelFontSize,'BackgroundColor',BackgroundColor);

ElemType_Text = uicontrol(PGD_Panel,'Style','text','String',...
    'Element Type','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','left',...
    'Position',[0 .67 .5 .32],'BackgroundColor',BackgroundColor);

ElemType_Value = uicontrol(PGD_Panel,'Style','text','String',...
    'none','FontUnits',FontUnits,'fontsize',PanelFontSize,'FontWeight','bold',...
    'Unit','normalized','HorizontalAlignment','left',...
    'Position',[.5 .67 .5 .32],'BackgroundColor',BackgroundColor);

PeriodRange_Text = uicontrol(PGD_Panel,'Style','text','String',...
    'Period Range','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','left',...
    'Position',[0 .34 .5 .32],'BackgroundColor',BackgroundColor);

PeriodRange_Value = uicontrol(PGD_Panel,'Style','text','String',...
    'none','FontUnits',FontUnits,'fontsize',PanelFontSize,'FontWeight','bold',...
    'Unit','normalized','HorizontalAlignment','left',...
    'Position',[.5 .34 .5 .32],'BackgroundColor',BackgroundColor);

DirectionRange_Text = uicontrol(PGD_Panel,'Style','text','String',...
    'Direction Range','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','left',...
    'Position',[0 .01 .5 .32],'BackgroundColor',BackgroundColor);

DirectionRange_Value = uicontrol(PGD_Panel,'Style','text','String',...
    'none','FontUnits',FontUnits,'fontsize',PanelFontSize,'FontWeight','bold',...
    'Unit','normalized','HorizontalAlignment','left',...
    'Position',[.5 .01 .5 .32],'BackgroundColor',BackgroundColor);
%--------------------------------------------------------------

%------------- Visualization
View_Panel = uipanel('Title','View Options','FontUnits',FontUnits,'BorderType',BorderType,...
    'TitlePosition','centertop','HighlightColor',PanelBorderColor,...
    'Position',[.685 .295 .15 .18],'FontSize',PanelFontSize,'BackgroundColor',BackgroundColor);

View_Axes = uicontrol(View_Panel,'Style','checkbox','Unit',...
    'normalized','FontUnits',FontUnits,'Position',[.01 0 .49 .2],'String',...
    'Axes','Enable','on','Value',0,'FontSize',PanelFontSize,'BackgroundColor',BackgroundColor);

View_Mesh = uicontrol(View_Panel,'Style','checkbox','Unit',...
    'normalized','FontUnits',FontUnits,'Position',[.01 .6 .49 .2],'String',...
    'Mesh','Enable','off','Value',0,'FontSize',PanelFontSize,'BackgroundColor',BackgroundColor);

View_Bottom = uicontrol(View_Panel,'Style','checkbox','Unit',...
    'normalized','FontUnits',FontUnits,'Position',[.01 .2 .49 .2],'String',...
    'Bottom','Enable','off','Value',0,'FontSize',PanelFontSize,'BackgroundColor',BackgroundColor);

View_Plot = uicontrol(View_Panel,'Style','checkbox','Unit',....
    'normalized','FontUnits',FontUnits,'Position',[.01 .8 .49 .2],'String',...
    'Plot','Enable','off','Value',0,'Fontsize',PanelFontSize,'BackgroundColor',BackgroundColor);

View_Background = uicontrol(View_Panel,'Style','checkbox','Unit',...
    'normalized','FontUnits',FontUnits,'Position',[.01 .4 .49 .2],'String',...
    'Background','Enable','off','Value',0,'FontSize',PanelFontSize,'BackgroundColor',BackgroundColor);

View_BC = uicontrol(View_Panel,'Style','popupmenu','FontUnits',FontUnits,'String',...
    {'Select Boundary'},'Value',1,'Unit','normalized','Position',[.51 0 .49 .2],...
    'Fontsize',PanelFontSize,'Enable','off');

View_PlotTransparency = uicontrol(View_Panel,'Style','slider','Min',0,'Max',1,'Value',1,'Enable','off',...
        'FontUnits',FontUnits,'String','Transparency','Unit','normalized','Position', [.51 .85 .49 .1]);
    
View_MeshTransparency = uicontrol(View_Panel,'Style','slider','Min',0,'Max',1,'Value',1,'Enable','off',...
        'FontUnits',FontUnits,'String','Transparency','Unit','normalized','Position', [.51 .65 .49 .1]);
    
View_BGTransparency = uicontrol(View_Panel,'Style','slider','Min',0,'Max',1,'Value',1,'Enable','off',...
        'FontUnits',FontUnits,'String','Transparency','Unit','normalized','Position', [.51 .45 .49 .1]);
    
View_BotTransparency = uicontrol(View_Panel,'Style','slider','Min',0,'Max',1,'Value',1,'Enable','off',...
        'FontUnits',FontUnits,'String','Transparency','Unit','normalized','Position', [.51 .25 .49 .1]);
%--------------------------------------------------------------

%------------- Incident Wave
Input_Panel = uipanel('Title','Incident Wave','Position',[.685 .6 .15 .39],'BorderType',BorderType,...
    'TitlePosition','centertop','HighlightColor',PanelBorderColor,...
    'FontUnits',FontUnits,'fontsize',PanelFontSize,'BackgroundColor',BackgroundColor);

Freq_Text = uicontrol(Input_Panel,'Style','text','String',...
    'Frequency [rad/s]:','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','left',...
    'Position',[.01 .27 .6 .08],'BackgroundColor',BackgroundColor);

Freq_Value = uicontrol(Input_Panel,'Style','edit','String',...
    'Value?','FontUnits',FontUnits,'fontsize',PanelFontSize,'FontWeight','bold',...
    'Unit','normalized','HorizontalAlignment','center',...
    'Position',[.6 .28 .32 .08],'Enable','on','BackgroundColor',BackgroundColor);

Period_Text = uicontrol(Input_Panel,'Style','text','String',...
    'Period [s]:','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','left',...
    'Position',[.01 .18 .6 .08],'BackgroundColor',BackgroundColor);

Period_Value = uicontrol(Input_Panel,'Style','edit','String',...
    'Value?','FontUnits',FontUnits,'fontsize',PanelFontSize,'FontWeight','bold',...
    'Unit','normalized','HorizontalAlignment','center',...
    'Position',[.6 .19 .32 .08],'Enable','on','BackgroundColor',BackgroundColor);

Direction_Text = uicontrol(Input_Panel,'Style','text','String',...
    'Direction [deg]:','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','left',...
    'Position',[.01 .09 .6 .08],'BackgroundColor',BackgroundColor);

Direction_Value = uicontrol(Input_Panel,'Style','edit','String',...
    'Value?','FontUnits',FontUnits,'fontsize',PanelFontSize,'FontWeight','bold',...
    'Unit','normalized','HorizontalAlignment','center',...
    'Position',[.6 .1 .32 .08],'Enable','on','BackgroundColor',BackgroundColor);

PGDTerms_Text = uicontrol(Input_Panel,'Style','text','String',...
    '# PGD terms:','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','left',...
    'Position',[.01 0 .6 .08],'BackgroundColor',BackgroundColor);

PGDTerms_Value = uicontrol(Input_Panel,'Style','edit','String',...
    'Value?','FontUnits',FontUnits,'fontsize',PanelFontSize,'FontWeight','bold',...
    'Unit','normalized','HorizontalAlignment','center',...
    'Position',[.6 .01 .32 .08],'Enable','on','BackgroundColor',BackgroundColor);
%--------------------------------------------------------------

%------------- Coordinates
Coord_Panel = uipanel('Position',[.55 .175 .12 .025],'BorderType','none',...
    'HighlightColor',PanelBorderColor,'BackgroundColor',BackgroundColor);

XCoord_Text = uicontrol(Coord_Panel,'Style','text','String',...
    'X','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','left',...
    'Position',[0 0 .1 1],'BackgroundColor',BackgroundColor);

XCoord_Value = uicontrol(Coord_Panel,'Style','text','String',...
    '0','FontUnits',FontUnits,'fontsize',PanelFontSize,'FontWeight','bold',...
    'Unit','normalized','HorizontalAlignment','center',...
    'Position',[.1 0 .4 1],'Enable','off','BackgroundColor',BackgroundColor);

YCoord_Text = uicontrol(Coord_Panel,'Style','text','String',...
    'Y','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','left',...
    'Position',[.5 0 .1 1],'BackgroundColor',BackgroundColor);

YCoord_Value = uicontrol(Coord_Panel,'Style','text','String',...
    '0','FontUnits',FontUnits,'fontsize',PanelFontSize,'FontWeight','bold',...
    'Unit','normalized','HorizontalAlignment','center',...
    'Position',[.6 0 .4 1],'Enable','off','BackgroundColor',BackgroundColor);
%--------------------------------------------------------------

%------------- Solution info
Info_Panel = uibuttongroup('Position',[.005 .175 .40 .025],'BorderType','none',...
    'HighlightColor',PanelBorderColor,'BackgroundColor',BackgroundColor);

Average_Text = uicontrol(Info_Panel,'Style','radiobutton','String',...
    'Avg.','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','left','Enable','off',...
    'Position',[.03 0 .15 1],'BackgroundColor',BackgroundColor);

Average_Value = uicontrol(Info_Panel,'Style','text','String',...
    'None','FontUnits',FontUnits,'fontsize',PanelFontSize,'FontWeight','bold',...
    'Unit','normalized','HorizontalAlignment','left','Enable','off',...
    'Position',[.19 0 .15 1],'Enable','off','BackgroundColor',BackgroundColor);

Minimum_Text = uicontrol(Info_Panel,'Style','radiobutton','String',...
    'Min.','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','left','Enable','off',...
    'Position',[.35 0 .15 1],'BackgroundColor',BackgroundColor);

Minimum_Value = uicontrol(Info_Panel,'Style','text','String',...
    'None','FontUnits',FontUnits,'fontsize',PanelFontSize,'FontWeight','bold',...
    'Unit','normalized','HorizontalAlignment','left','Enable','off',...
    'Position',[.51 0 .15 1],'Enable','off','BackgroundColor',BackgroundColor);

Maximum_Text = uicontrol(Info_Panel,'Style','radiobutton','String',...
    'Max.','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','left','Enable','off',...
    'Position',[.67 0 .15 1],'BackgroundColor',BackgroundColor);

Maximum_Value = uicontrol(Info_Panel,'Style','text','String',...
    'None','FontUnits',FontUnits,'fontsize',PanelFontSize,'FontWeight','bold',...
    'Unit','normalized','HorizontalAlignment','left','Enable','off',...
    'Position',[.83 0 .15 1],'Enable','off','BackgroundColor',BackgroundColor);
%--------------------------------------------------------------

%------------- User functions
% UserFcn_Panel = uipanel('Position',[.005 .12 .40 .025],'BorderType',BorderType,...
%     'HighlightColor',PanelBorderColor,'BackgroundColor',BackgroundColor);

UserFcn_Text = uicontrol('Style','text','String',...
    'User Function','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','left',...
    'Position',[.39 .15 .06 .05],'BackgroundColor',BackgroundColor);

UserFcn = uicontrol('Style','popupmenu','FontUnits',FontUnits,'String',...
    {'Select User Function'},'Value',1,'Unit','normalized','Position',[.45 .15 .08 .05],...
    'Fontsize',PanelFontSize,'Enable','on');
%--------------------------------------------------------------

Omega_Text = uicontrol('Style','text','String',...
    'Period Distribution','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','center','FontWeight','bold',...
    'Position',[.855 .725 .14 .02],'BackgroundColor',BackgroundColor);

Theta_Text = uicontrol('Style','text','String',...
    'Direction Distribution','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','center','FontWeight','bold',...
    'Position',[.855 .485 .14 .02],'BackgroundColor',BackgroundColor);

Plot3D_Text = uicontrol('Style','text','String',...
    'Period & Dir. Distribution','FontUnits',FontUnits,'fontsize',PanelFontSize,...
    'Unit','normalized','HorizontalAlignment','center','FontWeight','bold',...
    'Position',[.685 .27 .14 .02],'BackgroundColor',BackgroundColor);

%------------- Output panel
Output_Panel = uipanel('Title','Output','Position',[.005 .01 .67 .1],'BorderType',BorderType,...
    'TitlePosition','centertop','HighlightColor',PanelBorderColor,...
    'FontUnits',FontUnits,'fontsize',PanelFontSize,'BackgroundColor',BackgroundColor);

Text_Output = uicontrol(Output_Panel,'Style','listbox','FontUnits',FontUnits,'String',...
    {'Ready'},'Unit','normalized','Position',[0 0 1 1],'fontsize',PanelFontSize);
%--------------------------------------------------------------

%% Assign Tags

nTags = size(tags,1);
for item = 1:nTags
    itagString = tags{item,1};
    itag = eval(itagString);
    set(itag,'Tag',itagString)
end

%% Variables & Default Settings

dir_struct = struct('pgd',struct);
arrowdata = struct('p0',[0,0],'prev_p0',[0,0],'p0p',[0,0],'prev_p0p',[0,0],...
    'a1',[],'b1',[],'a0',[],'b0',[],'thetalim0',[],'thetalim1',[]);
data = struct('dir_struct',dir_struct,'plotid',[],'arrowid',[],'bottomid',[],'arrowdata',arrowdata,'backgroundid',[],...
    'userSelection',false,'Pointer',[],'CurrentTab',[],'PortNames',[],'PortCoordinates',[],'PortInfo',[],...
    'colorbarid',[],'PortMarkers',[],'ButtonFunctionsFlag',false,'location',[],'SelectionPoint',[],'bottom',[],...
    'Maximum',[],'Minimum',[],'meshid',[],'boundaryid',[],'graphid',[],'lineid',[],'solution',[],...
    'rectSelection',false,'rectSelectionid',[],'rectIniPoint',[],'surfid',[],'rectid',[],...
    'limitid',[],'limitlineid',[],'limitrectid',[]);
guidata(MainFigure,data);
handles = guihandles;

%% Set control functions
set(MainFigure,'WindowButtonDownFcn',{@MainFigureWindowButtonDownFcn,handles},...
               'WindowButtonUpFcn',{@MainFigureWindowButtonUpFcn,handles},...
               'WindowButtonMotionFcn',{@MainFigureWindowButtonMotionFcn,handles})

set(MainTabs,'SelectionChangedFcn',{@TabChangeFcn,handles})

linkprop([axesPlot1 axesPlot2 axesPlot3 axesPlot4],'View');
           
%% Callbacks

for item = 1:nTags
    itagString = tags{item,1};
    icall = tags{item,2};
    if icall
        itag = eval(itagString);
        ifun = str2func([itagString '_Callback']);
        if icall == 1
            set(itag,'Callback',{ifun,handles})
        elseif icall == 2
            set(itag,'ClickedCallback',{ifun,handles})
        elseif icall == 3
            set(itag,'SelectionChangeFcn',{ifun,handles})
        end
    end
end

%% Initialization
PGD_Dir = [pwd '/PGD_Data'];
axesArrow.Parent = Input_Panel;
initializeLocation(data,handles);
initializeUserFunctions(handles);
set(MainFigure,'Visible','on')